POST http://localhost:3001/api/diary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiI paste new token here
{
  "content": "Toinen Bearer autentikoitu muistiinpano",
  "important": false,
  "date": ""
}